// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIqvhGqUoLxtHNXXD80URU9qcDMDSB24M',
    appId: '1:42511618196:web:7d9dcc83c6a9315e6ae481',
    messagingSenderId: '42511618196',
    projectId: 'video-games-backlog',
    authDomain: 'video-games-backlog.firebaseapp.com',
    storageBucket: 'video-games-backlog.appspot.com',
    measurementId: 'G-TR47LWVCZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapYabI4OHn00jmpYBgX53PNneuMvrkuE',
    appId: '1:42511618196:android:b72c086efe6568cb6ae481',
    messagingSenderId: '42511618196',
    projectId: 'video-games-backlog',
    storageBucket: 'video-games-backlog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVbU4uN2XVYFRUh8SxUilCJ34UOJmmo94',
    appId: '1:42511618196:ios:b07afb142260e8a96ae481',
    messagingSenderId: '42511618196',
    projectId: 'video-games-backlog',
    storageBucket: 'video-games-backlog.appspot.com',
    iosClientId: '42511618196-rifa5k8b61sr24sljnoocd80p0l30tl2.apps.googleusercontent.com',
    iosBundleId: 'com.hieutran.videoGamesBacklog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVbU4uN2XVYFRUh8SxUilCJ34UOJmmo94',
    appId: '1:42511618196:ios:b07afb142260e8a96ae481',
    messagingSenderId: '42511618196',
    projectId: 'video-games-backlog',
    storageBucket: 'video-games-backlog.appspot.com',
    iosClientId: '42511618196-rifa5k8b61sr24sljnoocd80p0l30tl2.apps.googleusercontent.com',
    iosBundleId: 'com.hieutran.videoGamesBacklog',
  );
}
