// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQRzLFByp4yt5aHERXcdv3drNPfr_pFLE',
    appId: '1:588822565362:web:83e00ef48d358304addb6b',
    messagingSenderId: '588822565362',
    projectId: 'my-backlog-1040f',
    authDomain: 'my-backlog-1040f.firebaseapp.com',
    storageBucket: 'my-backlog-1040f.appspot.com',
    measurementId: 'G-6KT2Q3LBXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKyCC7JOCz9Dzua_W-0jERNwipxOwxn-s',
    appId: '1:588822565362:android:1222f54e381c9845addb6b',
    messagingSenderId: '588822565362',
    projectId: 'my-backlog-1040f',
    storageBucket: 'my-backlog-1040f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIp29ygRyFFrOHoyrYOE2iJFlWZtur10M',
    appId: '1:588822565362:ios:c9cb5129c7cf5d18addb6b',
    messagingSenderId: '588822565362',
    projectId: 'my-backlog-1040f',
    storageBucket: 'my-backlog-1040f.appspot.com',
    iosClientId: '588822565362-o7u0c4ne2cm9i2jj76a8l3es8lkqmbt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIp29ygRyFFrOHoyrYOE2iJFlWZtur10M',
    appId: '1:588822565362:ios:aefc9295c3388709addb6b',
    messagingSenderId: '588822565362',
    projectId: 'my-backlog-1040f',
    storageBucket: 'my-backlog-1040f.appspot.com',
    iosClientId: '588822565362-bkha4kkl98pb2a0fo35p7j4nit4t3nir.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGames',
  );
}
